# Generated by Django 4.2.3 on 2023-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV'), ('Book', 'Book')], default='', max_length=5)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
