# Generated by Django 4.2.3 on 2023-09-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='desc',
            new_name='description',
        ),
    ]
