# Generated by Django 4.2.3 on 2023-09-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_list_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='media',
        ),
        migrations.AddField(
            model_name='list',
            name='media',
            field=models.ManyToManyField(related_name='all_appearances', to='tracker.media'),
        ),
    ]
