# Generated by Django 4.2.3 on 2023-09-08 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_desc_list_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lists',
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
