# Generated by Django 4.2.3 on 2023-09-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_list_media_list_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='obj_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
