# Generated by Django 4.2.3 on 2023-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_list_user_list_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
