# Generated by Django 4.2.3 on 2023-09-30 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_media_obj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='all_media_reviews', to='tracker.media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
