# Generated by Django 4.2.3 on 2023-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_review_media_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
