# Generated by Django 4.2.3 on 2023-10-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
