# Generated by Django 4.2.3 on 2023-09-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_list_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
    ]
