# Generated by Django 4.2.3 on 2023-09-10 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
